# Stage 1
FROM node:20-alpine AS build-stage

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VUE_APP_API_GATEWAY_PROTOCOL
ARG VUE_APP_API_GATEWAY_ADDRESS
ARG VUE_APP_API_GATEWAY_PORT
ARG VUE_APP_FRONTEND_ADDRESS

ENV VUE_APP_API_GATEWAY_PROTOCOL=$VUE_APP_API_GATEWAY_PROTOCOL
ENV VUE_APP_API_GATEWAY_ADDRESS=$VUE_APP_API_GATEWAY_ADDRESS
ENV VUE_APP_API_GATEWAY_PORT=$VUE_APP_API_GATEWAY_PORT
ENV VUE_APP_FRONTEND_ADDRESS=$VUE_APP_FRONTEND_ADDRESS

RUN npm run build

# Stage 2
FROM nginx:stable-alpine AS production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
