const API_GATEWAY_PROTOCOL = process.env.VUE_APP_API_GATEWAY_PROTOCOL || 'http';
const API_GATEWAY_ADDRESS = process.env.VUE_APP_API_GATEWAY_ADDRESS || 'localhost';
const API_GATEWAY_PORT = process.env.VUE_APP_API_GATEWAY_PORT || '8002';

export const API_GATEWAY_URL = `${API_GATEWAY_PROTOCOL}://${API_GATEWAY_ADDRESS}:${API_GATEWAY_PORT}`;
